site_name: Basic tutorial for performing GWASs on DNAnexus
repo_url: https://github.com/gloriabenoit/DNAnexus-GWAS
site_author: Gloria BENOIT

nav:
    - Home: index.md
    - Initial setup: setup.md
    - Input files: input.md

theme:
  name: readthedocs

extra_css:
  - css/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'