site_name: Basic tutorial for performing a GWAS on DNAnexus
repo_url: https://github.com/gloriabenoit/DNAnexus-GWAS
site_author: Gloria BENOIT

nav:
    - Home: index.md
    - First setup: setup.md
    - About jobs: jobs.md
    - Input files: input.md
    - Using PLINK2: plink.md
    - Using regenie: regenie.md
    - Visualizing results: results.md

theme:
  name: readthedocs

extra_css:
  - css/extra.css
